<div id="sitefooter" class="row">
    <div class="col-lg-12">
        <hr>
        <p class="center"><small>© 2015 <a href="http://www.udb.edu.sv/udb/index.php">UDB</a></small></p>
        <p class="social-links center">
            <a href="https://www.facebook.com/UDBelsalvador" target="_blank" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook"><i class="fa fa-facebook"></i></a> &nbsp; 
            <a href="https://twitter.com/udbelsalvador" target="_blank" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter"><i class="fa fa-twitter"></i></a> &nbsp; 
            <a href="http://www.gmail.com" target="_blank" data-toggle="tooltip" data-placement="top" title="" data-original-title="Email"><i class="fa fa-envelope-o"></i></a>
        </p>
    </div>
</div>