<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <title>.:FileManager:.</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <link href="scripts/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link href="assets/stylesheet.css" rel="stylesheet" type="text/css"/>
        <link href="https://fonts.googleapis.com/css?family=Didact+Gothic|Source+Sans+Pro:200" rel="stylesheet" type="text/css">
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="scripts/html5shiv.js"></script>
        <script src="scripts/respond.min.js"></script>
        <style>.container {max-width: 960px}</style>
        <![endif]-->
    </head>