<header class="navbar navbar-fixed-top" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand sitename" href="#">File Manager</a>		
        </div>
        <nav class="sitenav collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <ul class="nav navbar-nav">
                <li><a href="MostrarTUsuarios.php">Tipo Usuario</a>
                    <ul>
                        <li><a href="TipoUsuarios.php">Nuevo Tipo Usuario</a>
                    </ul>
                </li>
                <li><a href="#">Archivos</a></li>
            </ul>
        </nav>
    </div>
</header>